### PR TITLE
Added the option to set App Pool recycle schedule(s) 

### PR DESCRIPTION
**Pull request by zuehlaa**
Added the option to set App Pool recycle schedule(s) which would look something like this
**restartSchedule = @("18:30:00")**

        cAppPool DemoAppPool
        {
            Name = "Demo App Pool"
            Ensure = "Present"
            autoStart = "true"  
            managedRuntimeVersion = "v4.0"
            managedPipelineMode = "Integrated"
            startMode = "AlwaysRunning"
            identityType = "ApplicationPoolIdentity"
            restartSchedule = @("18:30:00","05:00:00")
        }

Updated the sample cWebsite ps1 with a more detailed example, including some of the newer options

Also fixed some comments

### CODE REVIEW

**Comment by kevinsea** [comment]
Thanks.  I'm having some issues with this, I'll post my findings in the next day or so.

**Comment by kevinsea** [comment]
FWIW, I'm looking 2 things:
1) The change detection for schedule is always triggering.  I have a handle on that, its a minor tweek to the loop over the schedule.

2) I'm noticing all of those great new supported configuration params from the last commit are ending up in the IIS config file even when they are the default settings for a pool.  Normally when you create a pool with just basics, only the basics config end up in the IIS config file.  Rather that taking the default its overriding the defaults with the default values if that makes sense...its not terribly important but it makes the underlying config file noisy....what I'm working on separately is giving us the ability to generate a DSC/MOF files based on an existing server.  So a quiet, minimalist  config file makes it easy for me to prove to anyone that we can produce an exact clone of the source server.

**Comment by zuehlaa** [comment]
1)  I wasn't able to reproduce your issue, but I did find a much better way to do the test.  Give it a try now and see if you still have problems

2)  I see what you are saying here.  Right now the defaults are hard coded (not the best).  I'll see if I can query IIS for the defaults and then only write them if they are different.  Not sure if that is possible or not.

**Comment by kevinsea** [comment]
For #2, I think if you do the minimal create then run it through the update
code you should get the smaller config and will have less code too.

**Comment by kevinsea** [comment]
Regarding #1, I will check it out tonight.  In the meantime I have a
question about the code, specifically the use of this code

($PoolConfig.add.recycling.periodicRestart.schedule.add.value -ne $null)

don't you want to write this as:

($PoolConfig.recycling.periodicRestart.schedule -ne $null) ?

It seems like this is creating a new schedule and comparing to null, no?
 (I'm a C# coder that is just getting started with PS, so maybe I'm just
missing something?)

FWIW,this what I ended up with last night.

            if ((!$restartSchedule) -and
($PoolConfig.recycling.periodicRestart.schedule.length -eq 0))
                #if no time was requested, and we have no schedules => it
is a match
            {
                Write-Verbose("restartSchedule: No times passed, no changes
required");
            }
            elseif ($PoolConfig.recycling.periodicRestart.schedule.length
-ne $PoolConfig.recycling.periodicRestart.schedule.length )
                #if the number of restarts don't match, its a problem
            {
                $DesiredConfigurationMatch = $false
                Write-Verbose("restartSchedule of AppPool $Name does not
match the desired state (count).");
            }

            else #check each time requested and make sure its on the list
            {
                #First check to see if desired schedule times are currently
in the schedule
                foreach($time in $restartSchedule)
                {
                    Write-Verbose("restartSchedule: looking for: '$time'");

                    if ($time -ne "")
                    {
                        $schedExist = $false
                        foreach($schTime in
$PoolConfig.recycling.periodicRestart.schedule)
                        {
                            if($schTime -eq $time) {
                                $schedExist = $true
                                break
                            }
                        }
                        if($schedExist -eq $false){
                            $DesiredConfigurationMatch = $false
                            Write-Verbose("restartSchedule of AppPool $Name
does not match the desired state.");
                            break
                        }
                    }

                }
            }






On Thu, Mar 5, 2015 at 9:06 AM, Aaron Zuehlke <notifications@github.com>
wrote:
>
> 1) I wasn't able to reproduce your issue, but I did find a much better
way to do the test. Give it a try now and see if you still have problems
>
> 2) I see what you are saying here. Right now the defaults are hard coded
(not the best). I'll see if I can query IIS for the defaults and then only
write them if they are different. Not sure if that is possible or not.

**Comment by zuehlaa** [comment]
The actual xml looks something like this
```
<periodicRestart memory="0" privateMemory="0" requests="0" time="1.05:00:00">
        <schedule>
                 <add value="08:25:00" />
                 <add value="09:25:00" />
         </schedule>
</periodicRestart>
```
So $PoolConfig.add.recycling.periodicRestart.schedule.add.value actually returns an array of the times that are in there.  It is weird that "add" is the tag name.  So basically I have to make sure that it isn't going to return null instead of an array, otherwise the compare-object errors out.

I believe $PoolConfig.add.recycling.periodicRestart.schedule returns an xml object that would then have to be parsed.


For 2, if I create an app pool first and then do DSC on it, it does only write the non-default values.  Doing the same code inside the DSC Module is still putting all the values in there.  I'm pretty sure it can be done though, just need to figure out the right steps.

**Comment by kevinsea** [comment]
Ah, got it, thanks.

Regarding creating a new pool with a clean configuration, what I was
thinking would be to pare your current create code down just the basic and
do that first if needed:

            try
            {
                New-WebAppPool $Name
                Wait-Event -Timeout 5
                Stop-WebAppPool $Name

**Comment by kevinsea** [comment]
And I'm happy to code it and test if you'd prefer.

**Comment by zuehlaa** [comment]
Sure, feel free to see if you can get it working.  The best way to learn PS
is to jump right in.  I come from c# as well and PS takes a little getting
used to.  Definitely worth learning though

**Comment by kevinsea** [comment]
I created https://github.com/PowerShellOrg/cWebAdministration/pull/12 .  It creates a new pool without the extra config.  Thanks for the help.

**Pull request merged**
